# Ejercicios de practica NUMPY

### 1) Crear un arreglo con todos los números pares del 10 al 50.



In [16]:
import numpy as np
array1 = np.arange(10,51,2)
print("los numeros pares del 10 al 50 son: " + str(arr))

los numeros pares del 10 al 50 son: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


### 2) Crear un arreglo al azar de números enteros entre 0 y 100. Luego debemos calcular la media, mediana, desviación estándar, la suma de todos sus elementos.

In [20]:
array2 = np.random.randint(0, 101, size=10)
media = np.mean(array2)
mediana = np.percentile(array2,50)
desvest = np.std(array2)
suma = array2.sum()
print("el arreglo es: " + str(array2) + " su media es: " + str(media) + "\nsu mediana es: "+ str(mediana) + " su desvio estandar es: "+ str(desvest) + " y su suma es: " + str(suma))

el arreglo es: [27 69 41 46 67 85 32 70 80 64] su media es: 58.1
su mediana es: 65.5 su desvio estandar es: 19.14392854144624 y su suma es: 581


### 3) Crear una matriz con valores al azar entre 0 y 1, con forma 3x3.

In [26]:
matriz = np.random.rand(3,3)
print("la matriz con valores al azar entre 0 y 2 con forma 3 x 3 es\n" + str(matriz))

la matriz con valores al azar entre 0 y 2 con forma 3 x 3 es
[[0.90486133 0.60625773 0.62823734]
 [0.13422325 0.41203069 0.25717636]
 [0.0851092  0.14209467 0.93703849]]


### 4) Encontrar los valores mínimos y máximos de la anterior matriz



In [27]:
max = matriz.max()
min = matriz.min()
print ("el valor maximo es: " + str(max) + " y el valor minimo es : " +str(min))

el valor maximo es: 0.9370384868916896 y el valor minimo es : 0.08510920160095059


### 5) Crear un arreglo de 12 elementos, en el cual cada elemento refleje la inflación mensual durante el año 2022. Encontrar el valor mínimo, máximo, y media.

In [30]:
inflacion = np.array([3.9 , 4.7, 6.7, 6, 5.1, 7.4, 7, 6.2, 6.3, 4.9, 5.1])
inmax = inflacion.max()
inmin = inflacion.min()
inmedia = np.mean(inflacion)
print ("la inflacion de cada mes fue: " + str(inflacion)+ " el valor maximo es: " + str(inmax) + "\n el valor minimo es: " + str(inmin)+ " la media es es: " + str(inmedia))

la inflacion de cada mes fue: [3.9 4.7 6.7 6.  5.1 7.4 7.  6.2 6.3 4.9 5.1] el valor maximo es: 7.4
 el valor minimo es: 3.9 la media es es: 5.754545454545454
